import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        secondary: "#ffb59d",
        "secondary-fixed-dim": "#ffb59d",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed": "#ffdbd0",
        "surface-container-low": "#1a1c1c",
        "secondary-container": "#b83900",
        "on-tertiary-fixed-variant": "#544600",
        "on-secondary-fixed-variant": "#832600",
        "on-background": "#e2e2e2",
        "on-primary-fixed": "#0d1c32",
        "outline-variant": "#44474d",
        "on-primary": "#233148",
        "inverse-on-surface": "#2f3131",
        outline: "#8f9097",
        "tertiary-fixed-dim": "#e9c400",
        "surface-bright": "#37393a",
        "on-tertiary-container": "#4c3f00",
        "on-surface": "#e2e2e2",
        "surface-tint": "#b9c7e4",
        primary: "#b9c7e4",
        tertiary: "#e9c400",
        error: "#ffb4ab",
        surface: "#121414",
        "on-error": "#690005",
        "inverse-primary": "#515f78",
        "surface-container": "#1e2020",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#390c00",
        "surface-variant": "#333535",
        "on-secondary": "#5d1900",
        "surface-container-lowest": "#0c0f0f",
        "primary-container": "#0a192f",
        "surface-dim": "#121414",
        "on-primary-container": "#74829d",
        "surface-container-highest": "#333535",
        background: "#121414",
        "on-surface-variant": "#c5c6cd",
        "tertiary-container": "#c9a900",
        "error-container": "#93000a",
        "primary-fixed-dim": "#b9c7e4",
        "on-secondary-container": "#ffddd2",
        "inverse-surface": "#e2e2e2",
        "on-tertiary": "#3a3000",
        "on-primary-fixed-variant": "#39475f",
        "on-tertiary-fixed": "#221b00",
        "tertiary-fixed": "#ffe16d",
        "surface-container-high": "#282a2b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "4px",
        "container-max": "1440px",
        gutter: "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "telemetry-lg": ["JetBrains Mono"],
        "telemetry-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "telemetry-lg": [
          "18px",
          { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "telemetry-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
